### PR TITLE
Implement a basic TLS/SSL listener

### LINKED ISSUE #1: TLS daemon
In a language of your choice (I'd prefer Go due to less pain) write a daemon with the following CLI/config options:

* port
* TLS cert file
* TLS key file
* TLS CA cert file

The daemon shall:

* listen on the port
* accept connections
* perform a TLS handshake on each connection w/ the provided files

### PR DESCRIPTION
**Pull request by yhabteab**
resolves #1

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
And the CA cert?

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
1. Squash Your commits
2. Show how this behaves while using Icinga 2 certificates w/ openssl s_client (test protocol)

**Comment by yhabteab** [comment]
Testprotocol:

Start the test server: 
``./server -p 443 -pk /var/lib/icinga2/certs/ha-master.key -puk  /var/lib/icinga2/certs/ha-master.crt -ck /var/lib/icinga2/certs/ca.crt``

Server logs:
```bash
2020/12/08 14:22:07 SERVER: Started listening on '0.0.0.0:443'
```

Openssl command:
 ``openssl s_client -connect 127.0.0.1:443 -CAfile  /var/lib/icinga2/certs/ca.crt -cert /var/lib/icinga2/certs/ha-cluster.crt -key /var/lib/icinga2/certs/ha-cluster.key``

```bash
CONNECTED(00000003)
Can't use SSL_get_servername
depth=0 CN = ha-master
verify return:1
---
Certificate chain
 0 s:CN = ha-master
   i:CN = Icinga CA
---
Server certificate
-----BEGIN CERTIFICATE-----
[...]
-----END CERTIFICATE-----
subject=CN = ha-master

issuer=CN = Icinga CA

---
Acceptable client certificate CA names
CN = Icinga CA
Requested Signature Algorithms: RSA-PSS+SHA256:ECDSA+SHA256:Ed25519:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA384:ECDSA+SHA512:RSA+SHA1:ECDSA+SHA1
Shared Requested Signature Algorithms: RSA-PSS+SHA256:ECDSA+SHA256:Ed25519:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA384:ECDSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2158 bytes and written 3435 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 023E831C7D4AB4EE7A964D434B62E3210D6562E5BE462D24B51B5ED354637807
    Session-ID-ctx: 
    Resumption PSK: E5B0A557CEB8B1E11566F2CF62568618A83FFFA1791119AC080B1BE4577A7AD44D3A464B9DC61E54281491A102F3EBC8
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - d3 d5 fc 26 ab eb ab 74-e7 31 3b 56 f0 48 b3 a1   ...&...t.1;V.H..
[...]

Start Time: 1607434114
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
....
```

Server Logs:
```bash
2020/12/08 14:28:34 SERVER: Accepted connection from 127.0.0.1:56307
2020/12/08 14:28:34 SERVER: Connection approved from Server
2020/12/08 14:28:34 SERVER: Connection: Waiting for the client
```

Start to send some messages from the client:

```bash
read R BLOCK
Hello
Hello
Hello
I'm a test client
I'm a test client
I'm a test client
Can you give me some response
Can you give me some response
Can you give me some response
Yeah, sure
Yeah, sure
Yeah, sure
```

Server logs:

```bash
2020/12/08 14:29:13 SERVER: Connection: Received "Hello\n"
2020/12/08 14:29:13 SERVER: Connection: Sending 6 bytes
2020/12/08 14:29:13 SERVER: Connection: Waiting for the client
2020/12/08 14:29:55 SERVER: Connection: Received "I'm a test client\n"
2020/12/08 14:29:55 SERVER: Connection: Sending 18 bytes
2020/12/08 14:29:55 SERVER: Connection: Waiting for the client
2020/12/08 14:30:18 SERVER: Connection: Received "Can you give me some response\n"
2020/12/08 14:30:18 SERVER: Connection: Sending 30 bytes
2020/12/08 14:30:18 SERVER: Connection: Waiting for the client
2020/12/08 14:30:33 SERVER: Connection: Received "Yeah, sure\n"
2020/12/08 14:30:33 SERVER: Connection: Sending 11 bytes
2020/12/08 14:30:33 SERVER: Connection: Waiting for the client
```

**Review by Al2Klimov — APPROVED** [review]
Seems to do its thing.

**Pull request merged**
